server:
  port: 8080

info:
  app:
    name: "Riggs"
    description: "This is an application to management hotel booking"
    version: 1.0

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true
    database: mysql
  datasource:
    url: jdbc:mysql-vuby:3306
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


#  datasource:
#    url: jdbc:mysql://localhost:3306/riggs
#    username: root
#    password: developer


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /riggs/admin
  endpoint:
    health:
      show-details: always

jwt:
  securityKey: '6E5A7234753778214125432A462D4A614E645267556B58703273357638792F42'
  tokenPrefix: 'Bearer'
  accessTokenExpirationDate: 86400000
  refreshTokenExpirationDate: 604800000

