server:
  port: 8080

info:
  app:
    name: "Hotel Booking System"
    description: "This is an application to management hotel booking"
    version: 1.0

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/riggs
    username: root
    password: developer

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /riggs
  endpoint:
    health:
      show-details: always
